language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
os:
  - linux
  - osx
  - windows
before_install:
  - |
      if [ "$TRAVIS_OS_NAME" == "windows" ]; then
        /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/14.15.26726/bin/HostX64/vcvarsall.bat x86
      fi
