[package]
name = "hanbaiki"
version = "0.1.1"
authors = ["mikong <michaelgalero@gmail.com>", "Mithi Sevilla <mithi.sevilla@gmail.com>"]
publish = false

[dependencies]
clap = "2.32.0"

[dev-dependencies]
rand = "0.5"
lazy_static = "1.1.0"
